version: '3.5'

service: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-project
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules